language: php

php:
- 7.0
- 7.1

sudo: false

env:
- ILLUMINATE_VERSION=^5.1 TESTBENCH_VERSION=^3.1 ELASTICSEARCH_VERSION=^2
- ILLUMINATE_VERSION=^5.2 TESTBENCH_VERSION=^3.2 ELASTICSEARCH_VERSION=^2
- ILLUMINATE_VERSION=^5.3 TESTBENCH_VERSION=^3.3 ELASTICSEARCH_VERSION=^2
- ILLUMINATE_VERSION=^5.4 TESTBENCH_VERSION=^3.4 ELASTICSEARCH_VERSION=^2
- ILLUMINATE_VERSION=^5.5 TESTBENCH_VERSION=^3.5 ELASTICSEARCH_VERSION=^2
- ILLUMINATE_VERSION=^5.6 TESTBENCH_VERSION=^3.6 ELASTICSEARCH_VERSION=^2
- ILLUMINATE_VERSION=^5.1 TESTBENCH_VERSION=^3.1 ELASTICSEARCH_VERSION=^5
- ILLUMINATE_VERSION=^5.2 TESTBENCH_VERSION=^3.2 ELASTICSEARCH_VERSION=^5
- ILLUMINATE_VERSION=^5.3 TESTBENCH_VERSION=^3.3 ELASTICSEARCH_VERSION=^5
- ILLUMINATE_VERSION=^5.4 TESTBENCH_VERSION=^3.4 ELASTICSEARCH_VERSION=^5
- ILLUMINATE_VERSION=^5.5 TESTBENCH_VERSION=^3.5 ELASTICSEARCH_VERSION=^5
- ILLUMINATE_VERSION=^5.6 TESTBENCH_VERSION=^3.6 ELASTICSEARCH_VERSION=^5
- ILLUMINATE_VERSION=^5.1 TESTBENCH_VERSION=^3.1 ELASTICSEARCH_VERSION=^6
- ILLUMINATE_VERSION=^5.2 TESTBENCH_VERSION=^3.2 ELASTICSEARCH_VERSION=^6
- ILLUMINATE_VERSION=^5.3 TESTBENCH_VERSION=^3.3 ELASTICSEARCH_VERSION=^6
- ILLUMINATE_VERSION=^5.4 TESTBENCH_VERSION=^3.4 ELASTICSEARCH_VERSION=^6
- ILLUMINATE_VERSION=^5.5 TESTBENCH_VERSION=^3.5 ELASTICSEARCH_VERSION=^6
- ILLUMINATE_VERSION=^5.6 TESTBENCH_VERSION=^3.6 ELASTICSEARCH_VERSION=^6

matrix:
  exclude:
  - php: 7.0
    env: ILLUMINATE_VERSION=^5.6 TESTBENCH_VERSION=^3.6 ELASTICSEARCH_VERSION=^2
  - php: 7.0
    env: ILLUMINATE_VERSION=^5.6 TESTBENCH_VERSION=^3.6 ELASTICSEARCH_VERSION=^5
  - php: 7.0
    env: ILLUMINATE_VERSION=^5.6 TESTBENCH_VERSION=^3.6 ELASTICSEARCH_VERSION=^6

install:
- phpenv config-rm xdebug.ini
- travis_retry composer global require hirak/prestissimo
- travis_retry composer require elasticsearch/elasticsearch:${ELASTICSEARCH_VERSION} illuminate/support:${ILLUMINATE_VERSION}
- travis_retry composer require --dev orchestra/testbench:${TESTBENCH_VERSION}

script: composer run coverage

after_script:
- vendor/bin/test-reporter

cache:
  directories:
  - vendor
  - "$HOME/.composer/cache"
