language: php

php:
- 7.0
- 7.1

sudo: false

git:
  depth: 3

env:
- ILLUMINATE_SUBVERSION=4 ELASTICSEARCH_VERSION=2
- ILLUMINATE_SUBVERSION=5 ELASTICSEARCH_VERSION=2
- ILLUMINATE_SUBVERSION=6 ELASTICSEARCH_VERSION=2
- ILLUMINATE_SUBVERSION=7 ELASTICSEARCH_VERSION=2
- ILLUMINATE_SUBVERSION=4 ELASTICSEARCH_VERSION=5
- ILLUMINATE_SUBVERSION=5 ELASTICSEARCH_VERSION=5
- ILLUMINATE_SUBVERSION=6 ELASTICSEARCH_VERSION=5
- ILLUMINATE_SUBVERSION=7 ELASTICSEARCH_VERSION=5
- ILLUMINATE_SUBVERSION=4 ELASTICSEARCH_VERSION=6
- ILLUMINATE_SUBVERSION=5 ELASTICSEARCH_VERSION=6
- ILLUMINATE_SUBVERSION=6 ELASTICSEARCH_VERSION=6
- ILLUMINATE_SUBVERSION=7 ELASTICSEARCH_VERSION=6

matrix:
  exclude:
  - php: 7.0
    env: ILLUMINATE_SUBVERSION=6 ELASTICSEARCH_VERSION=2
  - php: 7.0
    env: ILLUMINATE_SUBVERSION=6 ELASTICSEARCH_VERSION=5
  - php: 7.0
    env: ILLUMINATE_SUBVERSION=6 ELASTICSEARCH_VERSION=6
  - php: 7.0
    env: ILLUMINATE_SUBVERSION=7 ELASTICSEARCH_VERSION=2
  - php: 7.0
    env: ILLUMINATE_SUBVERSION=7 ELASTICSEARCH_VERSION=5
  - php: 7.0
    env: ILLUMINATE_SUBVERSION=7 ELASTICSEARCH_VERSION=6
  fast_finish: true

before_install:
- phpenv config-rm xdebug.ini
- composer config -g github-oauth.github.com "${GITHUB_TOKEN}"
- travis_retry composer global require hirak/prestissimo

install:
- cp "lockfiles/php-${TRAVIS_PHP_VERSION}-laravel-5.${ILLUMINATE_SUBVERSION}-es-${ELASTICSEARCH_VERSION}.lock" composer.lock
- composer update --lock

script: composer run test

cache:
  directories:
  - "$HOME/.composer/cache/files"
  - "$HOME/.cache/composer/files"
